### ISSUE TITLE
As a developer, I would like to create count of words in the pdf so that, the user can easily check the word count in the pdf.

### ISSUE THREAD

**Issue by snehamirupala** [Team-Bob7/AirViewer2-master#13]
## Todo

- [ ] Define a class with a functionality to counting words PDFs.
- [ ] Testing the functionality of counting words PDFs and provide the code coverage.
- [ ] Adding a button to UI which allows user to counting words PDFs.
