### ISSUE TITLE
As a developer, I would like to compress the pdf so that, it is easy to reduce the size and make it easier to send them via email or other online channels.

### ISSUE THREAD

**Issue by snehamirupala** [Team-Bob7/AirViewer2-master#5]
## Todo

- [ ] Define a class with functionality to compress the PDFs.
- [ ] Testing the functionality of compress PDFs and provide the code coverage.
- [ ] Adding a button to UI which allows the user to compress PDFs.
